export { default as ImgIcon } from './ImgIcon'
export { default as TabItem } from './TabItem'
export * from './Seperators'
export { default as CText } from './TextComp'
export { default as EmptyComponent } from './EmptyComponent'
export { default as FullScreenLoader } from './FullScreenLoader'
export { default as Loader } from './Loader'
// export { default as ImgBadge } from './ImgBadge'
export { default as IconComp } from './IconComp'
export { default as DefaultPattern } from './DefaultPattern'
export { default as RowItem } from './RowItem'
export { default as ImgOrText } from './ImgOrText'
export { default as TopTabsBar } from './TopTabsBar'